REVOKE USAGE ON SCHEMA net FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA net FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA net REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
